### ISSUE TITLE
Needed to change LDFLAGS to LDLIBS in Makefile to build on Ubuntu

### ISSUE THREAD

**Issue by M-a-r-k** [ribalda/fx2eeprom#3]
I needed to change LDFLAGS to LDLIBS in the Makefile to build on Ubuntu 16.04.

**Comment by ribalda** [comment]
Thanks for your comment. Somehow it ended up deep down on my mail and I failed to reply. Sorry about that.

I have just fixed it, and also added a docker image in case you want to test it with a debian/stable build.

Thanks!
